name: Deploy to Production

on:
  push:
    branches: [ "main" ]  # 只在main分支推送时触发

env:
  DOCKER_COMPOSE_VERSION: 1.29.2
  SSH_PORT: 22  # 默认SSH端口，如有修改请调整

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 安装SSH密钥
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 连接到服务器并执行部署命令
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ env.SSH_PORT }} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "cd ${{ secrets.PROJECT_DIR }} && \
               git pull origin main && \
               docker-compose -f deploy/docker-compose/docker-compose.yaml up --build -d && \
               docker system prune -f"
